"""empty message

Revision ID: 1a04c33971aa
Revises: d1c1e08e0e42
Create Date: 2019-05-30 23:45:50.465808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a04c33971aa'
down_revision = 'd1c1e08e0e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('bill_first_name', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('bill_last_name', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('bill_postcode', sa.String(length=4), nullable=False))
    op.add_column('payment', sa.Column('bill_street_address', sa.String(length=50), nullable=False))
    op.add_column('payment', sa.Column('credit_name', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('delivery_first_name', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('delivery_last_name', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('delivery_postcode', sa.String(length=4), nullable=False))
    op.add_column('payment', sa.Column('delivery_street_address', sa.String(length=50), nullable=False))
    op.drop_column('payment', 'bpostcode')
    op.drop_column('payment', 'dpostcode')
    op.drop_column('payment', 'blast_name')
    op.drop_column('payment', 'cname')
    op.drop_column('payment', 'dstreet_address')
    op.drop_column('payment', 'dlast')
    op.drop_column('payment', 'bstreet_address')
    op.drop_column('payment', 'dfirst')
    op.drop_column('payment', 'bfirst_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('bfirst_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('dfirst', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('bstreet_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('dlast', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('dstreet_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('cname', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('blast_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('dpostcode', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('bpostcode', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_column('payment', 'delivery_street_address')
    op.drop_column('payment', 'delivery_postcode')
    op.drop_column('payment', 'delivery_last_name')
    op.drop_column('payment', 'delivery_first_name')
    op.drop_column('payment', 'credit_name')
    op.drop_column('payment', 'bill_street_address')
    op.drop_column('payment', 'bill_postcode')
    op.drop_column('payment', 'bill_last_name')
    op.drop_column('payment', 'bill_first_name')
    # ### end Alembic commands ###
