"""empty message

Revision ID: 25be896c001b
Revises: 
Create Date: 2019-04-16 09:18:30.483158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25be896c001b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('test', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
