"""empty message

Revision ID: 444c2327356e
Revises: 274efb51521e
Create Date: 2019-05-25 19:08:18.617178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444c2327356e'
down_revision = '274efb51521e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shipmentdetails', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipmentdetails', type_='unique')
    # ### end Alembic commands ###
