"""empty message

Revision ID: 49b6be6a8edf
Revises: 67145b9e7241
Create Date: 2019-05-31 02:19:27.638842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b6be6a8edf'
down_revision = '67145b9e7241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    # ### end Alembic commands ###
