"""empty message

Revision ID: 50b5dd2cebd4
Revises: f64926e6d4b8
Create Date: 2019-05-23 15:02:35.753093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50b5dd2cebd4'
down_revision = 'f64926e6d4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraccesslog',
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('log_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['accountId'], ['account.id'], ),
    sa.PrimaryKeyConstraint('accountId', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useraccesslog')
    # ### end Alembic commands ###
