"""empty message

Revision ID: 521dddb2cde5
Revises: 814859678aec
Create Date: 2019-05-31 02:04:44.363981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521dddb2cde5'
down_revision = '814859678aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('daddress', sa.String(length=100), nullable=False))
    op.drop_column('payment', 'dstreet_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('dstreet_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('payment', 'daddress')
    # ### end Alembic commands ###
