"""empty message

Revision ID: 53c385ec97fc
Revises: 1234f1286f49
Create Date: 2019-05-31 17:29:03.436907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c385ec97fc'
down_revision = '1234f1286f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['id'])
    op.create_unique_constraint(None, 'genre', ['id'])
    op.create_unique_constraint(None, 'maturityrating', ['id'])
    op.create_unique_constraint(None, 'movie', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'payment', ['id'])
    op.create_unique_constraint(None, 'paymentmethod', ['id'])
    op.create_unique_constraint(None, 'shipmentdetails', ['id'])
    op.create_unique_constraint(None, 'useraccesslog', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useraccesslog', type_='unique')
    op.drop_constraint(None, 'shipmentdetails', type_='unique')
    op.drop_constraint(None, 'paymentmethod', type_='unique')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'movie', type_='unique')
    op.drop_constraint(None, 'maturityrating', type_='unique')
    op.drop_constraint(None, 'genre', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
