"""empty message

Revision ID: 611f68cf28b7
Revises: 444c2327356e
Create Date: 2019-05-29 21:17:36.880197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '611f68cf28b7'
down_revision = '444c2327356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipmentdetails', 'order_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipmentdetails', 'order_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
