"""empty message

Revision ID: 67145b9e7241
Revises: 86bd269d50d1
Create Date: 2019-05-31 02:19:16.118056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67145b9e7241'
down_revision = '86bd269d50d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dfirst', sa.String(length=20), nullable=False),
    sa.Column('dlast', sa.String(length=20), nullable=False),
    sa.Column('daddress', sa.String(length=100), nullable=False),
    sa.Column('dpostcode', sa.String(length=4), nullable=False),
    sa.Column('credit_name', sa.String(length=20), nullable=False),
    sa.Column('credit_no', sa.String(length=16), nullable=False),
    sa.Column('cvc', sa.String(length=3), nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('bfirst_name', sa.String(length=20), nullable=False),
    sa.Column('blast_name', sa.String(length=20), nullable=False),
    sa.Column('bstreet_address', sa.String(length=50), nullable=False),
    sa.Column('bpostcode', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
