"""empty message

Revision ID: 6e0a8ba1f600
Revises: 484ae7f0dd3e
Create Date: 2019-04-17 07:08:01.820633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0a8ba1f600'
down_revision = '484ae7f0dd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('is_staff', sa.Boolean(), nullable=False))
    op.add_column('movie', sa.Column('postcode', sa.Integer(), nullable=False))
    op.add_column('movie', sa.Column('street_address', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'movie', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='unique')
    op.drop_column('movie', 'street_address')
    op.drop_column('movie', 'postcode')
    op.drop_column('movie', 'is_staff')
    # ### end Alembic commands ###
