"""empty message

Revision ID: 814859678aec
Revises: 3b8b9a1a3bf4
Create Date: 2019-05-31 01:37:04.274585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814859678aec'
down_revision = '3b8b9a1a3bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    # ### end Alembic commands ###
