"""empty message

Revision ID: 814f71972292
Revises: 1a04c33971aa
Create Date: 2019-05-31 00:13:44.007375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814f71972292'
down_revision = '1a04c33971aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('bfirst_name', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('blast_name', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('bpostcode', sa.String(length=4), nullable=False))
    op.add_column('payment', sa.Column('bstreet_address', sa.String(length=50), nullable=False))
    op.add_column('payment', sa.Column('dfirst', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('dlast', sa.String(length=20), nullable=False))
    op.add_column('payment', sa.Column('dpostcode', sa.String(length=4), nullable=False))
    op.add_column('payment', sa.Column('dstreet_address', sa.String(length=50), nullable=False))
    op.drop_column('payment', 'bill_postcode')
    op.drop_column('payment', 'bill_first_name')
    op.drop_column('payment', 'bill_last_name')
    op.drop_column('payment', 'delivery_last_name')
    op.drop_column('payment', 'delivery_street_address')
    op.drop_column('payment', 'bill_street_address')
    op.drop_column('payment', 'delivery_postcode')
    op.drop_column('payment', 'delivery_first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('delivery_first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('delivery_postcode', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('bill_street_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('delivery_street_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('delivery_last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('bill_last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('bill_first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('bill_postcode', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_column('payment', 'dstreet_address')
    op.drop_column('payment', 'dpostcode')
    op.drop_column('payment', 'dlast')
    op.drop_column('payment', 'dfirst')
    op.drop_column('payment', 'bstreet_address')
    op.drop_column('payment', 'bpostcode')
    op.drop_column('payment', 'blast_name')
    op.drop_column('payment', 'bfirst_name')
    # ### end Alembic commands ###
