"""empty message

Revision ID: 98c9e085b1b9
Revises: beb2a2946cca
Create Date: 2019-05-23 15:31:26.656588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98c9e085b1b9'
down_revision = 'f64926e6d4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraccesslog',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('accountId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('log_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['accountId'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useraccesslog')
    # ### end Alembic commands ###
