"""empty message

Revision ID: af5142e9d477
Revises: 5372237f07b4
Create Date: 2019-05-31 11:33:59.793230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5142e9d477'
down_revision = '5372237f07b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('creditno', sa.String(length=16), nullable=False))
    op.create_unique_constraint(None, 'payment', ['id'])
    op.drop_column('payment', 'credit_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('credit_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'creditno')
    # ### end Alembic commands ###
