"""empty message

Revision ID: b685462f6fa2
Revises: e253515c9517
Create Date: 2019-04-18 20:34:47.338346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b685462f6fa2'
down_revision = 'e253515c9517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moviecopy', sa.Column('movieId', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'moviecopy', 'movie', ['movieId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moviecopy', type_='foreignkey')
    op.drop_column('moviecopy', 'movieId')
    # ### end Alembic commands ###
