"""empty message

Revision ID: d1c1e08e0e42
Revises: 5372237f07b4
Create Date: 2019-05-30 23:31:56.329607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c1e08e0e42'
down_revision = '5372237f07b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    # ### end Alembic commands ###
