"""empty message

Revision ID: d6ed9ede728e
Revises: b685462f6fa2
Create Date: 2019-04-19 17:21:36.936335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ed9ede728e'
down_revision = 'b685462f6fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maturityrating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maturity_rating', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('movie', sa.Column('maturity_rating', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'movie', 'maturityrating', ['maturity_rating'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'maturity_rating')
    op.drop_table('maturityrating')
    # ### end Alembic commands ###
