"""empty message

Revision ID: ea30c4be2b42
Revises: 5fdb7eccc5ea
Create Date: 2019-05-25 18:39:07.900215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea30c4be2b42'
down_revision = '5fdb7eccc5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'useraccesslog', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useraccesslog', type_='unique')
    # ### end Alembic commands ###
