"""empty message

Revision ID: f64926e6d4b8
Revises: d6ed9ede728e
Create Date: 2019-05-22 15:35:18.511583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64926e6d4b8'
down_revision = 'd6ed9ede728e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('account', sa.Column('join_date', sa.Date(), nullable=False))
    op.add_column('account', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('account', sa.Column('username', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'account', ['email'])
    op.create_unique_constraint(None, 'account', ['username'])
    op.create_unique_constraint(None, 'maturityrating', ['id'])
    op.add_column('movie', sa.Column('release_date', sa.Date(), nullable=False))
    op.add_column('movie', sa.Column('thumbnail_src', sa.String(length=150), nullable=False))
    op.drop_column('movie', 'releaseDate')
    op.drop_column('movie', 'thumbnailSrc')
    op.add_column('orders', sa.Column('tracking_status', sa.String(length=50), nullable=False))
    op.drop_column('orders', 'trackingStatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trackingStatus', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('orders', 'tracking_status')
    op.add_column('movie', sa.Column('thumbnailSrc', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('movie', sa.Column('releaseDate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('movie', 'thumbnail_src')
    op.drop_column('movie', 'release_date')
    op.drop_constraint(None, 'maturityrating', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'username')
    op.drop_column('account', 'phone_number')
    op.drop_column('account', 'join_date')
    op.drop_column('account', 'is_active')
    # ### end Alembic commands ###
